export const mockProducts = [
  {
    id: 1,
    title: 'Classic Cotton T-Shirt',
    price: 19.99,
    category: 'clothing',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.3, count: 120 },
  },
  {
    id: 2,
    title: 'Slim Fit Jeans',
    price: 39.99,
    category: 'clothing',
    image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    rating: { rate: 4.1, count: 89 },
  },
  {
    id: 3,
    title: 'Running Sneakers',
    price: 64.5,
    category: 'footwear',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.6, count: 210 },
  },
  {
    id: 4,
    title: 'Leather Wallet',
    price: 24.0,
    category: 'accessories',
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: { rate: 4.2, count: 54 },
  },
  {
    id: 5,
    title: 'Wireless Headphones',
    price: 89.99,
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.7, count: 310 },
  },
  {
    id: 6,
    title: 'Bluetooth Speaker',
    price: 49.99,
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    rating: { rate: 4.5, count: 178 },
  },
  {
    id: 7,
    title: 'Office Backpack',
    price: 44.9,
    category: 'bags',
    image: 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg',
    rating: { rate: 4.4, count: 132 },
  },
  {
    id: 8,
    title: 'Travel Duffel Bag',
    price: 59.9,
    category: 'bags',
    image: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg',
    rating: { rate: 4.0, count: 76 },
  },
  {
    id: 9,
    title: 'Smart Watch',
    price: 129.99,
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    rating: { rate: 4.3, count: 160 },
  },
  {
    id: 10,
    title: 'Polarized Sunglasses',
    price: 34.25,
    category: 'accessories',
    image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    rating: { rate: 4.1, count: 64 },
  },
  {
    id: 11,
    title: 'Minimal Desk Lamp',
    price: 27.5,
    category: 'home',
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    rating: { rate: 4.2, count: 98 },
  },
  {
    id: 12,
    title: 'Ceramic Coffee Mug',
    price: 12.99,
    category: 'home',
    image: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
    rating: { rate: 4.0, count: 143 },
  },
  {
    id: 13,
    title: 'Yoga Mat Pro',
    price: 29.9,
    category: 'sports',
    image: 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg',
    rating: { rate: 4.5, count: 111 },
  },
  {
    id: 14,
    title: 'Stainless Water Bottle',
    price: 18.75,
    category: 'sports',
    image: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
    rating: { rate: 4.6, count: 201 },
  },
  {
    id: 15,
    title: 'Gaming Mouse',
    price: 45.99,
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61xWwQxQxkL._AC_SX679_.jpg',
    rating: { rate: 4.4, count: 187 },
  },
  {
    id: 16,
    title: 'Mechanical Keyboard',
    price: 79.0,
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
    rating: { rate: 4.8, count: 224 },
  },
];
